
from telegram.inline.inlinekeyboardbutton import InlineKeyboardButton


DEVELOPER_CHAT_ID = 999273250


STICKERS = {
    "PENNY_PUG_SAD": 'CAACAgIAAxkBAAECUm1gpqI8kLliVJDBKnXGNBULtWJm5AACIwADnP4yMGLSFbgqnabRHwQ',
    "PENNY_PUG_ANXIOUS": 'CAACAgIAAxkBAAECUn1gpq6x1tbqKFEd5Ts5FctSDEhz7gACIQADnP4yMOQGvNtSSJXGHwQ',
    "PENNY_PUG_HEART_BROKEN": "CAACAgIAAxkBAAECUpZgprh8TrZloaChwZn6DTMc99ooeAACHAADnP4yMJbopn7Nh5taHwQ",
    "PENNY_PUG_THUMBS_UP": "CAACAgIAAxkBAAECUqZgptE6hiQaUZ7jnM3fjikTitWdLAACCgADnP4yMFsQVnkk-4rwHwQ"
}


# Stages
PREPARE_GAME, IN_GAME = range(2)

# Callback data
JOIN, START, EXIT, CURRENT_POLL = range(4)


MAIN_MENU_KEYBOARD = [
    [
        InlineKeyboardButton("Unirse", callback_data=str(JOIN)),
        InlineKeyboardButton("Empezar", callback_data=str(START)),
    ],
    [InlineKeyboardButton("X", callback_data=str(EXIT))],
]

MAIN_MENU_IN_GAME = [
    [InlineKeyboardButton("Repetir pregunta",
                          callback_data=str(CURRENT_POLL))],
    [InlineKeyboardButton("X", callback_data=str(EXIT))],
]

QUESTIONS = [
    {"q": "¿Quién es más probable que mate a alguien accidentalmente?"},
    {"q": "¿Quién es más probable que no le gusten mucho las películas?"},
    {"q": "¿Quién es más probable que se convierta en un famoso actor/actriz?"},
    {"q": "¿Quién es más probable que huya para no unirse al circo?"},
    {"q": "¿Quién es más probable que salte de un tren en movimiento?"},
    {"q": "¿Quién es más probable que tenga paranoias?"},
    {"q": "¿Quién es más probable que sea el más atlético?"},
    {"q": "¿Quién es más probable que vea películas románicas?"},
    {"q": "¿Quién es más probable que se convierta en un stripper?"},
    {"q": "¿Quién es más probable que sea detenido por acosar a un oficial de policía?"},
    {"q": "¿Quién es más probable que sea inseguro?"},
    {"q": "¿Quién es más probable que sea arrastrado por un oso?"},
    {"q": "¿Quién es más probable que sea el más emocional?"},
    {"q": "¿Quién es más probable que sea adicto a los juegos de azar?"},
    {"q": "¿Quién es más probable que haya besado primero a un chico/a una chica?"},
    {"q": "¿Quién es más probable que sea mejor en matemáticas?"},
    {"q": "¿Quién sería probablemente el que estuviera incómoda en su primera cita?"},
    {"q": "¿Quién sería probablemente la que jugara en la “WNBA”?"},
    {"q": "¿Quién es más probable que sea exitoso como comentarista?"},
    {"q": "¿Quién sería probablemente la mujer más poderosa y mejor considerada del mundo?"},
    {"q": "¿Quién es más probable que se encuentre un fantasma?"},
    {"q": "¿Quién es más probable que este borracho en el trabajo?"},
    {"q": "¿Quién sería probablemente el más rico?"},
    {"q": "¿Quién es más probable que robe un banco?"},
    {"q": "¿Quién es más probable que se convierta un luchador?"},
    {"q": "¿Quién sería probablemente el que viviese más tiempo?"},
    {"q": "¿Quién sería probablemente el que fuese a un club gay?"},
    {"q": "¿Quién es más probable que sea sádico?"},
    {"q": "¿Quién es más probable que se meta en una pelea?"},
    {"q": "¿Quién sería probablemente el que ande dormido?"},
    {"q": "¿Quién es más probable que se disguste por una estúpida razón?"},
    {"q": "¿Quién es más probable que salga absuelto tras haber cometido un asesinato?"},
    {"q": "¿Quién sería probablemente el que se convierta en CEO de una empresa clasificada entre las 100 más grandes del mundo?"},
    {"q": "¿Quién será probablemente el que se haga un gran actor/actriz?"},
    {"q": "¿Quién es más probable que sea el más sarcástico?"},
    {"q": "¿Quién es más probable que no se duche en una semana?"},
    {"q": "¿Quién sería probablemente al que le encantaría difundir un rumor?"},
    {"q": "¿Quién es más probable que este siempre feliz?"},
    {"q": "¿Quién es más probable que sea el más creativo?"},
    {"q": "¿Quién es más probable que deje en ridículo a un amigo en público?"},
    {"q": "¿Quién es más probable que no tenga un ordenador?"},
    {"q": "¿Quién sería probablemente el que pruebe un trío?"},
    {"q": "¿Quién es más probable que se olvide de los cumpleaños importantes?"},
    {"q": "¿Quién es más probable que cuide a los demás cuando están enfermos?"},
    {"q": "¿Quién es más probable que se enamore de su mejor amigo/a?"},
    {"q": "¿Quién sería probablemente el que nunca quiera tener un bebé?"},
    {"q": "¿Quién es más probable que sea el primero en casarse?"},
    {"q": "¿Quién es más probable que se case con una celebridad?"},
    {"q": "¿Quién es más probable que se lea todos los libros de la biblioteca del colegio?"},
    {"q": "¿Quién es más probable que invente algo útil?"},
    {"q": "¿Quién es más probable que encuentre fácil ganar unas elecciones?"},
    {"q": "¿Quién es más probable que sea el más sensible?"},
    {"q": "¿Quién es más probable que cause una guerra mundial?"},
    {"q": "¿Quién es más probable que adopte un niño?"},
    {"q": "¿Quién es más probable que tenga muchos hermanos y hermanas?"},
    {"q": "¿Quién sería probablemente un filántropo?"},
    {"q": "¿Quién es más probable que sea el primero en morir en un apocalipsis de zombis?"},
    {"q": "¿Quién es más probable que tenga citas con dos chicos a la vez?"},
    {"q": "¿Quién es más probable que sea el más atento?"},
    {"q": "¿Quién es más probable que se haga cirugía plástica?"},
    {"q": "¿Quién es más probable que vaya a un concierto de Justin Bieber?"},
    {"q": "¿Quién es más probable que tenga un trabajo a tiempo parcial?"},
    {"q": "¿Quién es más probable que se case sin amor?"},
    {"q": "¿Quién es más probable que se convierta en una monja?"},
    {"q": "¿Quién es más probable que haga cosas raras en público?"},
    {"q": "¿Quién es más probable que gane una medalla olímpica?"},
    {"q": "¿Quién es más probable que gane un Oscar?"},
    {"q": "¿Quién es más probable que llegue tarde a su boda?"},
    {"q": "¿Quién es más probable que se preocupe por pequeñas cosas?"},
    {"q": "¿Quién es más probable que supere algún récord mundial?"},
    {"q": "¿Quién es más probable que sea rico?"},
    {"q": "¿Quién es más probable que aguante su respiración el mayor tiempo posible?"},
    {"q": "¿Quién es más probable que viva en un zoo?"},
    {"q": "¿Quién es más probable que se ría en el momento equivocado?"},
    {"q": "¿Quién es más probable que muera por algo estúpido?"},
    {"q": "¿Quién es más probable que haya sido siempre un rompe corazones?"},
    {"q": "¿Quién es más probable que gobierne el mundo?"},
    {"q": "¿Quién es más probable que se una al ejército?"},
    {"q": "¿Quién es más probable que sea un humorista?"},
    {"q": "¿Quién es más probable que sea el más chistoso?"},
    {"q": "¿Quién es más probable que fume?"},
    {"q": "¿Quién será probablemente el que sea incapaz de guardar un secreto durante 30 minutos?"},
    {"q": "¿Quién es más probable que haga puénting?"},
    {"q": "¿Quién es más probable que se escabulla de un viaje de chicas para coquetear con un extraño?"},
    {"q": "¿Quién es más probable que haga un cambio?"},
    {"q": "¿Quién sería probablemente al que nunca inviten a una fiesta de cumpleaños?"},
    {"q": "¿Quién es más probable que obtenga el premio nacional más prestigioso del país?"},
    {"q": "¿Quién sería probablemente el que se haría más tatuajes?"},
    {"q": "¿Quién es más probable que tenga un reality show?"},
    {"q": "¿Quién es más probable que gane un premio Novel?"},
    {"q": "¿Quién es más probable que ponga los cuernos con el prometido de su mejor amiga?"},
    {"q": "¿Quién es más probable que sea el primero en ser desvirgado?"},
    {"q": "¿Quién es más probable que se una al servicio secreto?"},
    {"q": "¿Quién es más probable que se una a una banda?"},
    {"q": "¿Quién es más probable que tenga más niños?"},
    {"q": "¿Quién es más probable que sea el mejor mentiroso?"},
    {"q": "¿Quién es más probable que sea un viajero del mundo?"},
    {"q": "¿Quién sería probablemente el que se tiña el pelo de rojo?"},
    {"q": "¿Quién es más probable que tome drogas?"},
    {"q": "¿Quién es más probable que hable con los animales?"},
    {"q": "¿Quién es más probable que establezca una ley científica?"},
    {"q": "¿Quién es más probable que mire porno nada más al levantarse?"},
    {"q": "¿Quién es más probable que sea pobre?"},
    {"q": "¿Quién es más probable que sea un cerebrito?"},
    {"q": "¿Quién es más probable que se gaste todo su dinero en algo estúpido?"},
    {"q": "¿Quién sería probablemente el que nunca vaya a la universidad?"},
    {"q": "¿Quién es más probable que se mude a un país diferente?"},
    {"q": "¿Quién sería probablemente el que tuviese una serpiente como mascota?"},
    {"q": "¿Quién será probablemente el que nunca se case?"},
    {"q": "¿Quién es más probable que que tenga fobias raras?"},
    {"q": "¿Quién es más probable que se convierta en multimillonario?"},
    {"q": "¿Quién es más probable que viva en una gran ciudad?"},
    {"q": "¿Quién es más probable que todo su dinero a la caridad?"},
    {"q": "¿Quién sería probablemente el que sea admitido en un hospital psiquiátrico?"},
    {"q": "¿Quién es más probable que le dé un puñetazo a la pared?"},
    {"q": "¿Quién es más probable que coma con la boca abierta?"},
    {"q": "¿Quién es más probable que llore en un lugar público?"},
    {"q": "¿Quién es más probable que llore con una película triste?"},
    {"q": "¿Quién es más probable que tenga más piercings?"},
    {"q": "¿Quién es más probable que se case con un narcotraficante?"},
    {"q": "¿Quién es más probable que llame al trabajo y diga que está enfermo para ir a un concierto en otra ciudad?"},
    {"q": "¿Quién es más probable que sea más bonita que una sirena?"},
    {"q": "¿Quién es más probable que sea arrestado por andar desnudo por la calle?"},
    {"q": "¿Quién es más probable que nunca haya estado enamorado?"},
    {"q": "¿Quién es más probable que sea reconocido por el récord mundial de Guinness?"},
    {"q": "¿Quién es más probable que tenga dos novias al mismo tiempo?"},
    {"q": "¿Quién es más probable que le dé un infarto por ver una película de terror?"},
    {"q": "¿Quién es más probable que salga en un anuncio publicitario?"},
    {"q": "¿Quién es más probable que se avergüence de sí mismo delante de su amor secreto / conocido?"},
    {"q": "¿Quién es más probable que sea un perfeccionista?"},
    {"q": "¿Quién sería probablemente el que ganase un Grammy?"},
    {"q": "¿Quién es más probable que suspenda un examen fácil?"},
    {"q": "¿Quién es más probable que fume marihuana?"},
    {"q": "¿Quién es más probable que se convierta en la persona más amable del mundo?"},
    {"q": "¿Quién es más probable que se vaya de gira mundial?"},
    {"q": "¿Quién es más probable que haga un millón de dólares?"},
    {"q": "¿Quién es más probable que se suicide por un escándalo?"},
    {"q": "¿Quién es más probable que le toque la lotería?"},
    {"q": "¿Quién es más probable que se convierta en una super modelo?"},
    {"q": "¿Quién es más probable que sea una dramática?"},
    {"q": "¿Quién es más probable que se convierta en alcohólico?"},
    {"q": "¿Quién es más probable que se convierta en profesor de instituto?"},
    {"q": "¿Quién es más probable que se convierta en presidente de los Estados Unidos de América?"},
    {"q": "¿Quién es más probable que se quede dormido en clase?"},
    {"q": "¿Quién es más probable que acabe en la cárcel?"},
    {"q": "¿Quién es más probable que vaya al museo a menudo?"},
    {"q": "¿Quién es más probable que sea el primero en comprarse un coche?"},
    {"q": "¿Quién sería probablemente la que tenga el novio más guapo?"},
    {"q": "¿Quién es más probable que sea el mejor panadero?"},
    {"q": "¿Quién es más probable que escriba un libro y se convierta en el más vendido?"},
    {"q": "¿Quién es más probable que aparezca en un programa de televisión?"},
    {"q": "¿Quién es más probable que escuche música clásica?"},
    {"q": "¿Quién es más probable que se opere para un cambio de sexo?"},
    {"q": "¿Quién es más probable que cante en un coro?"},
    {"q": "¿Quién es más probable que se divorcie en menos de una semana después de su boda?"},
    {"q": "¿Quién es más probable que se convierta en un semental?"},
    {"q": "¿Quién es más probable que se convierta en un abusón?"},
    {"q": "¿Quién es más probable que se quede atascado en un baño o en un ascensor?"},
    {"q": "¿Quién es más probable que vaya a pescar?"},
    {"q": "¿Quién es más probable que no se duche en una semana?"},
    {"q": "¿Quién es más probable que se convierta en un actor mundialmente famoso (o actriz) algún día?"},
    {"q": "¿Quién es más probable que se duerma viendo la tv?"},
    {"q": "¿Quién es más probable que sea un rompe corazones?"},
    {"q": "¿Quién es más probable que se convierta en millonario?"},
    {"q": "¿Quién es más probable que convertirse en un maestro de ajedrez?"},
    {"q": "¿Quién es más probable que se convierta en un divorciado?"},
    {"q": "¿Quién es más probable que se convierta en un atleta profesional?"},
    {"q": "¿Quién es más probable que se convierta en un alienígena?"},
    {"q": "¿Quién es más probable que acabe con el mundo?"},
    {"q": "¿Quién es más probable que olvide donde aparcó el coche?"},
    {"q": "¿Quién es más probable que finja su muerte?"},
    {"q": "¿Quién es más probable que use zapatos disparejos como declaración a la moda?"},
    {"q": "¿Quién es más probable que desarrolle un hábito de picar entre horas?"},
    {"q": "¿Quién es más probable que se quede en la cama todo el día?"},
    {"q": "¿Quién es más probable que se convierta en un poeta?"},
    {"q": "¿Quién es más probable que le guste un compañero de trabajo?"},
    {"q": "¿Quién es más probable que se convierta en un humorista?"},
    {"q": "¿Quién es más probable que se convierta en un alcohólico?"},
    {"q": "¿Quién es más probable que se convierta vegetariano?"},
    {"q": "¿Quién es más probable que se convierta en multi millonario?"},
    {"q": "¿Quién es más probable que se deje el fuego puesto al salir de casa?"},
    {"q": "¿Quién es más probable que viva en la Antártida?"},
    {"q": "¿Quién es más probable que sea arrestado durante sus vacaciones por la policía?"},
    {"q": "¿Quién es más probable que limpie la mierda de todo el mundo sin preguntar?"},
    {"q": "¿Quién es más probable que ronque más fuerte?"},
    {"q": "¿Quién es más probable que se meta en pelea?"},
    {"q": "¿Quién es más probable que se caiga del escenario en un evento televisivo?"},
    {"q": "¿Quién es más probable que gane un concurso de pedos?"},
    {"q": "¿Quién es más probable que que se vuelva adicto a los lácteos?"},
    {"q": "¿Quién es más probable que se convierta en político?"},
    {"q": "¿Quién es más probable que se enganche a las drogas?"},
    {"q": "¿Quién es más probable que sea alérgico a los gatos/perros?"},
    {"q": "¿Quién es más probable que mate a su pareja si le es infiel?"},
    {"q": "¿Quién es más probable que entre en la lista de delincuentes sexuales?"},
    {"q": "¿Quién es más probable que posea un camión?"},
    {"q": "¿Quién es más probable que haga algo estúpido en una noche con sus hijos?"},
    {"q": "¿Quién es más probable que se quede en casa un viernes noche?"},
    {"q": "¿Quién es más probable que sea el más buscavidas?"},
    {"q": "¿Quién es más probable que gaste más en comida?"},
    {"q": "¿Quién es más probable que sea terrible como secretario de defensa?"},
    {"q": "¿Quién es más probable que pierda mucho tiempo con su pelo?"},
    {"q": "¿Quién es más probable que cambie de tema al profesor?"},
    {"q": "¿Quién es más probable que espíe a su amor platónico?"},
    {"q": "¿Quién es más probable que se convierta en un bebé de nuevo?"},
    {"q": "¿Quién es más probable que se coma algo del suelo?"},
    {"q": "¿Quién es más probable que tenga un millón de seguidores en su red social?"},
    {"q": "¿Quién es más probable que tenga un hijo antes del matrimonio?"},
    {"q": "¿Quién es más probable que sea un melodramático/a?"},
    {"q": "¿Quién es más probable que tenga más tatuajes?"},
    {"q": "¿Quién es más probable que grite por una araña?"},
    {"q": "¿Quién es más probable que se olvide de un evento importante?"},
    {"q": "¿Quién es más probable que se quede embarazada de un lio de una noche y tenga al niño?"},
    {"q": "¿Quién es más probable que enloquezca en un centro comercial?"},
    {"q": "¿Quién es más probable que sea dueño de un bar?"},
    {"q": "¿Quién es más probable que se convierta en un científico malvado?"},
    {"q": "¿Quién es más probable que se case con un extranjero para obtener la “Green Card”?"},
    {"q": "¿Quién es más probable que sea un actor malo?"},
    {"q": "¿Quién es más probable que desarrolle la costumbre de decir “umm” y “ahh”?"},
    {"q": "¿Quién es más probable que este ausente en las funciones familiares?"},
    {"q": "¿Quién es más probable que tenga sentimientos por un lio de una sola noche?"},
    {"q": "¿Quién es más probable que sea un alienígena?"},
    {"q": "¿Quién es más probable que se convierta en policía?"},
    {"q": "¿Quién es más probable que se convierta en un famoso actor/actriz?"},
    {"q": "¿Quién es más probable que desarrolle la costumbre de morderse las uñas?"},
    {"q": "¿Quién es más probable que haga snowboard?"},
    {"q": "¿Quién es más probable que mienta, incluso cuando dice que dice la verdad?"},
    {"q": "¿Quién es más probable que se case primero?"},
    {"q": "¿Quién es más probable que viva con una tribu indígena?"},
    {"q": "¿Quién es más probable que se convierta en una “Blogger” de viajes?"},
    {"q": "¿Quién es más probable que se tire el mayor tiempo sin comer nada?"},
    {"q": "¿Quién es más probable que tenga niños en los siguientes 5 años?"},
    {"q": "¿Quién es más probable que se convierta en un famoso?"},
    {"q": "¿Quién es más probable que se olvide de maquillarse?"},
    {"q": "¿Quién es más probable que vaya a una misión espacial?"},
    {"q": "¿Quién es más probable que se olvide del nombre de las personas?"},
    {"q": "¿Quién es más probable que le quede bien una falda escocesa?"},
    {"q": "¿Quién es más probable que tenga trillizos?"},
    {"q": "¿Quién es más probable que sea alérgico a los gatos/perros?"},
    {"q": "¿Quién es más probable que desarrolle la costumbre de comprobar su pelo/cejas/maquillaje/uñas?"},
    {"q": "¿Quién es más probable que se convierta en un cantante famoso?"},
    {"q": "¿Quién es más probable que se convierta en un activista por los derechos de los animales?"},
    {"q": "¿Quién es más probable que coma cuando este aburrido/a?"},
    {"q": "¿Quién es más probable que sea un desastre comiendo?"},
    {"q": "¿Quién es más probable que acabe en Broadway?"},
    {"q": "¿Quién es más probable que le griten sus padres?"},
    {"q": "¿Quién es más probable que nade desnudo en el océano?"},
    {"q": "¿Quién es más probable que viva en una gran ciudad?"},
    {"q": "¿Quién es más probable que sea un soplón?"},
    {"q": "¿Quién es más probable que se haga pipi fuera de la taza del váter?"},
    {"q": "¿Quién es más probable que se lo tome todo al pie de la letra?"},
    {"q": "¿Quién es más probable que se convierta en una sacerdote/monja?"},
    {"q": "¿Quién es más probable que se coma algo asqueroso por un reto?"},
    {"q": "¿Quién es más probable que le pillen escapándose?"},
    {"q": "¿Quién es más probable que le destruya la casa una tormenta?"},
    {"q": "¿Quién es más probable que desarrolle la manía de comer más de la cuenta?"},
    {"q": "¿Quién es más probable que disfrute picoteando por la noche muy tarde?"},
    {"q": "¿Quién es más probable que acabe solo/a?"},
    {"q": "¿Quién es más probable que robe un banco?"},
    {"q": "¿Quién es más probable que sea arrestado por culpa de una apuesta?"},
    {"q": "¿Quién es más probable que se enamore de su profesor en la universidad?"},
    {"q": "¿Quién es más probable que acabe siendo adicto a los caramelos?"},
    {"q": "¿Quién es más probable que se invente una historia falsa?"},
    {"q": "¿Quién es más probable que acabe siendo adicto a las drogas?"},
    {"q": "¿Quién es más probable que gane un concurso de comer pasteles?"},
    {"q": "¿Quién es más probable que abandone su habitación por una araña?"},
    {"q": "¿Quién es más probable que gaste todo su dinero en ropa?"},
    {"q": "¿Quién es más probable que tropiece por las escaleras?"},
    {"q": "¿Quién es más probable que se limpie los diente en público?"},
    {"q": "¿Quién es más probable que se quede despierto hasta tarde jugando a los videojuegos?"},
    {"q": "¿Quién es más probable que se olvide de ir a comprar?"},
    {"q": "¿Quién es más probable que sea un fotógrafo horrible?"},
    {"q": "¿Quién es más probable que se convierta e n un super héroe?"},
    {"q": "¿Quién es más probable que se enamore de un profesor?"},
    {"q": "¿Quién es más probable que practique surf?"},
    {"q": "¿Quién es más probable que se canse de su pareja después de dos semanas?"},
    {"q": "¿Quién es más probable que se haga adicto a los m&m’s?"},
    {"q": "¿Quién es más probable que delate a uno de sus hermanos?"},
    {"q": "¿Quién es más probable que hable con la boca llena?"},
    {"q": "¿Quién es más probable que cree el hábito de no lavarse los dientes?"},
    {"q": "¿Quién es más probable que renuncie a su objetivo fitness?"},
    {"q": "¿Quién es más probable que tarde más en arreglarse"},
    {"q": "¿Quién es más probable que tenga hambre en mitad de la noche?"},
    {"q": "¿Quién es más probable que se convierta en conserje de una escuela?"},
    {"q": "¿Quién es más probable que tenga una pesadilla antes de la semana que viene?"},
    {"q": "¿Quién es más probable que tenga un yate?"},
    {"q": "¿Quién es más probable que se case con un famoso?"},
    {"q": "¿Quién es más probable que haga el ridículo delante de su amor platónico?"},
    {"q": "¿Quién es más probable que pida una pizza en las próximas 24 horas?"},
    {"q": "¿Quién es más probable que que se coma una pizza entera en menos de media hora?"},
    {"q": "¿Quién es más probable que abra un regalo antes de la fecha establecida?"},
    {"q": "¿Quién es más probable que grite como un loco en una montaña rusa?"},
    {"q": "¿Quién es más probable que viva 100 años?"},
    {"q": "¿Quién es más probable que haga topless en la playa?"},
    {"q": "¿Quién es más probable que sea adicto a los clubes?"},
    {"q": "¿Quién es más probable que abra un orfanato?"},
    {"q": "¿Quién es más probable que se convierta en ateo?"},
    {"q": "¿Quién es más probable que se duerma en plena cita?"},
    {"q": "¿Quién es más probable que se convierta en actor?"},
    {"q": "¿Quién es más probable que se duerma rezando?"},
    {"q": "¿Quién es más probable que se caiga en la ducha?"},
    {"q": "¿Quién es más probable que se convierta en un paciente psiquiátrico?"},
    {"q": "¿Quién es más probable que le haga frente a un matón?"},
    {"q": "¿Quién es más probable que se pase con las bromas?"},
    {"q": "¿Quién es más probable que abra un restaurante de lujo?"},
    {"q": "¿Quién es más probable que le den un puñetazo en la cara?"},
    {"q": "¿Quién es más probable que finja una enfermedad?"},
    {"q": "¿Quién es más probable que vea una película con su amor platónico?"},
    {"q": "¿Quién es más probable que sea la mascota del profesor?"},
    {"q": "¿A quién es más probable que le roben el coche?"},
    {"q": "¿Quién es más probable que sea muy indeciso a la hora de tomar decisiones?"},
    {"q": "¿Quién es más probable que sea dueño de una casa en la playa?"},
    {"q": "¿Quién es más probable que se convierta en piloto?"},
    {"q": "¿Quién es más probable que se enamore del hombre lobo?"},
    {"q": "¿Quién es más probable que bese a su amor platónico?"},
    {"q": "¿Quién es más probable que se enganche la los cigarrillos?"},
    {"q": "¿Quién es más probable que se tire todo el día jugando a los videos juegos?"},
    {"q": "¿Quién es más probable que se enamore de un stripper?"},
    {"q": "¿Quién es más probable que se salte las comidas?"},
    {"q": "¿Quién es más probable que sea un buen padre?"},
    {"q": "¿Quién es más probable que se convierta en una estrella del rock?"},
    {"q": "¿Quién es más probable que sea acosado?"},
    {"q": "¿Quién es más probable que se fume un porro en un lugar público?"},
    {"q": "¿Quién es más probable que se coma una uña del pie?"},
    {"q": "¿Quién es más probable que vaya de gira mundial?"},
    {"q": "¿Quién es más probable que se convierta en un stripper?"},
    {"q": "¿Quién es más probable que este de mal humor después de una aventura de una sola noche?"},
    {"q": "¿Quién es más probable que necesite más tiempo en una tienda?"},
    {"q": "¿Quién es más probable que se convierta en presidente?"},
    {"q": "¿Quién es más probable que acabe siendo adicto a “Reddit”?"},
    {"q": "¿Quién es más probable que compre el mismo regalo más de una vez?"},
    {"q": "¿Quién es más probable que se haga adicto a la productividad?"},
    {"q": "¿Quién es más probable que vea dos veces una película con diferentes chicas?"},
    {"q": "¿Quién es más probable que se convierta en un caza fortunas?"},
    {"q": "¿Quién es más probable que se case con una estrella del rock?"},
    {"q": "¿Quién es más probable que desarrolle la manía obsesiva de mirar el móvil constantemente?"},
    {"q": "¿Quién es más probable que se olvide ducharse?"},
    {"q": "¿Quién es más probable que haga de “El Grinch” en Navidad?"},
    {"q": "¿Quién es más probable que se avergüence cuando este delante de la persona que le gusta?"},
    {"q": "¿Quién es más probable que coma comida de gato?"},
    {"q": "¿Quién es más probable que se caiga de un árbol?"},
    {"q": "¿Quién es más probable que desarrolle el hábito de morder su bolígrafo?"},
    {"q": "¿Quién es más probable que sea golpeado por una bicicleta?"},
    {"q": "¿Quién es más probable que desarrolle el hábito de crujirse los nudillos?"},
    {"q": "¿Quién es más probable que haga una maratón de películas la noche antes de un examen importante?"},
    {"q": "¿Quién es más probable que se convierta en una figura pública?"},
    {"q": "¿Quién es más probable que se convierta adicto al te?"},
    {"q": "¿Quién es más probable que aceche al famoso del que está enamorado/a?"},
    {"q": "¿Quién es más probable que se deje las llaves dentro del coche?"},
    {"q": "¿Quién es más probable que se convierta en un agente secreto?"},
    {"q": "¿Quién es más probable que se enamore de un personaje anime?"},
    {"q": "¿Quién es más probable que coma la comida de perro?"},
    {"q": "¿Quién es más probable que llore durante una pelea?"},
    {"q": "¿Quién es más probable que se convierta en una estrella de Bollywood?"},
    {"q": "¿Quién es más probable que se ponga triste a causa de la muerte de un animal?"},
    {"q": "¿Quién es más probable que se afeite la cabeza por alguna razón?"},
    {"q": "¿Quién es más probable que ayude a un amigo a enterrar un cuerpo?"},
    {"q": "¿Quién es más probable que suspenda el examen de coche?"},
    {"q": "¿Quién es más probable que se haga asquerosamente rico?"},
    {"q": "¿Quién es más probable que exagere muchísimo la realidad?"},
    {"q": "¿Quién es más probable que escuche a escondidas una conversación?"},
    {"q": "¿Quién es más probable que sea un mal policía?"},
    {"q": "¿Quién es más probable que se olvide su cartera/monedero en una tienda?"},
    {"q": "¿Quién es más probable que sea el más gritón en un juego?"},
    {"q": "¿Quién es más probable que se enamore de la persona equivocada?"},
    {"q": "¿Quién es más probable que sea dueño de una mascota rara?"},
    {"q": "¿Quién es más probable que se coma una pizza entera él/ella mismo en menos de media hora?"},
    {"q": "¿Quién es más probable que se convierta en “El Grinch” en Navidad?"},
    {"q": "¿Quién es más probable que renuncie a su asiento en el tren para cedérselo a una persona mayor?"},
    {"q": "¿Quién es más probable que abra un estudio de yoga?"},
    {"q": "¿Quién es más probable que actúe como super héroe en una película de Marvel?"},
    {"q": "¿Quién es más probable que bese a su mejor amigo/a?"},
    {"q": "¿Quién es más probable que cree la manía de saltarse el desayuno?"},
    {"q": "¿Quién es más probable que olvide el cumpleaños de su esposa?"},
    {"q": "¿Quién es más probable que se haga miembro de la Unión Estadounidense de Libertades Civiles?"},
    {"q": "¿Quién es más probable que coma comida rara?"},
    {"q": "¿Quién es más probable que vea una película de miedo solo/a?"},
    {"q": "¿Quién es más probable que tenga un negocio ilegal?"},
    {"q": "¿Quién es más probable que ladre en público?"},
    {"q": "¿Quién es más probable que se haga famoso?"},
    {"q": "¿Quién es más probable que llegue tarde a la graduación?"},
    {"q": "¿Quién es más probable que aparente los años que realmente tiene?"},
    {"q": "¿Quién es más probable que acabe con el hambre en el mundo?"},
    {"q": "¿Quién es más probable que se convierta en mago?"},
    {"q": "¿Quién es más probable que se bañe desnudo en invierno cuando este nevando?"},
    {"q": "¿Quién es más probable que se haga adicto al café?"},
    {"q": "¿Quién es más probable que ayude a un ladrón a escapar?"},
    {"q": "¿Quién es más probable que rompa la pantalla de su móvil?"},
    {"q": "¿Quién es más probable que sea dueño de un zoo?"},
    {"q": "¿Quién es más probable que se convierta en un/una super modelo?"},
    {"q": "¿Quién es más probable que tenga el mayor número de piercings?"},
    {"q": "¿Quién es más probable que utilice a los niños como excusa para salir de un compromiso?"},
    {"q": "¿Quién es más probable que sea algo torpe cuando esta con los suegros?"},
    {"q": "¿Quién es más probable que tenga el coeficiente intelectual más bajo?"},
    {"q": "¿Quién es más probable que se haga a dicto a comer comida basura?"},
    {"q": "¿Quién es más probable que cree la manía de morder su boli?"},
    {"q": "¿Quién es más probable que traicione a su mejor amigo?"},
    {"q": "¿Quién es más probable que vuelva a enseñar en su instituto?"},
    {"q": "¿Quién es más probable que se coma algo que esté vivo?"},
    {"q": "¿Quién es más probable que se haga adicto a Facebook?"},
    {"q": "¿Quién es más probable que se abra una cuenta de Instagram?"},
    {"q": "¿Quién es más probable que sea dueño de un salón de belleza?"},
    {"q": "¿Quién es más probable que asuste a un ladrón?"},
    {"q": "¿Quién es más probable que se olvide su cartera/monedero en un atienda?"},
    {"q": "¿Quién es más probable que se coma el mayor número de hamburguesas en menos de minutos?"},
    {"q": "¿Quién es más probable que bese a un camarero/a?"},
    {"q": "¿Quién es más probable que se olvide de lavar los platos?"},
    {"q": "¿Quién es más probable que vuelva a mudarse con sus padres?"},
    {"q": "¿Quién es más probable que vea una película de miedo solo por la noche?"},
    {"q": "¿Quién es más probable que se case con un gay que no ha salido del armario?"},
    {"q": "¿Quién es más probable que se quede hasta altas horas de la madrugada mandándose mensajes eróticos con cualquier desconocido por internet?"},
    {"q": "¿Quién es más probable que se case con alguien que sus familia y amigos odian?"},
    {"q": "¿Quién es más probable que actúe como villano en una película?"},
    {"q": "¿Quién es más probable que viva en una jungla?"},
    {"q": "¿Quién es más probable que se convierta en un jugador profesional?"},
    {"q": "¿Quién es más probable que se olvide del cumpleaños de su madre?"},
    {"q": "¿Quién es más probable que se convierta en miembro de la Asociación Nacional del Rifle?"},
    {"q": "¿Quién es más probable que se duerma viendo una película?"},
    {"q": "¿Quién es más probable que diga algo tonto y vergonzoso en público?"},
    {"q": "¿Quién es más probable que coma comida de perro?"},
    {"q": "¿Quién es más probable que se olvide de su aniversario de bodas?"},
    {"q": "¿Quién es más probable que se salte la escuela?"},
    {"q": "¿Quién es más probable que haga una huelga de hambre?"},
    {"q": "¿Quién es más probable que tenga una pistola?"},
    {"q": "¿Quién es más probable que se convierta en bombero?"},
    {"q": "¿Quién es más probable que se salte el toque de queda?"},
    {"q": "¿Quién es más probable que se convierta en humorista?"},
    {"q": "¿Quién es más probable que desarrolle la manía de pellizcarse la piel?"},
    {"q": "¿Quién es más probable que meta en un lío a toda la pandilla?"},
    {"q": "¿Quién es más probable que se quite la vida por un desamor?"},
    {"q": "¿Quién es más probable que se convierta en un asesino en serie?"},
    {"q": "¿Quién es más probable que permanezca dormido mientras suena la alarma?"},
    {"q": "¿Quién es más probable que finja hasta que lo consiga?"},
    {"q": "¿Quién es más probable que se vuelva un adicto emocional a las compras?"},
    {"q": "¿Quién es más probable que se convierta en un profesor de instituto?"},
    {"q": "¿Quién es más probable que se avergüence cuando él/ ella está cerca de su amor platónico?"},
    {"q": "¿Quién es más probable que suspenda un examen fácil?"},
    {"q": "¿Quién es más probable que siga adelante con una relación tóxica?"},
    {"q": "¿Quién es más probable que sea el más crítico?"},
    {"q": "¿Quién es más probable que se quede dormido viendo la tv?"},
    {"q": "¿Quién es más probable que sea un terrible secretario del estado?"},
    {"q": "¿Quién es más probable que vaya por su cuenta en una noche de fiesta?"},
    {"q": "¿Quién es más probable que se ofenda por una broma?"},
    {"q": "¿Quién es más probable que se quede encerrado fuera de casa?"},
    {"q": "¿Quién es más probable que se caiga por las escaleras?"},
    {"q": "¿Quién es más probable que viva hasta los 100 años?"},
    {"q": "¿Quién es más probable que se convierta en un parásito?"},
    {"q": "¿Quién es más probable que se canse de su pareja después de dos semanas?"},
    {"q": "¿Quién es más probable que se convierta en un “troll” de internet?"},
    {"q": "¿Quién es más probable que cancele a sus amigos?"},
    {"q": "¿Quién es más probable que le roben?"},
    {"q": "¿Quién es más probable que mienta para salir de un problema?"},
    {"q": "¿Quién es más probable que sea el alma de la fiesta?"},
    {"q": "¿Quién es más probable que se haga famoso por algo estúpido?"},
    {"q": "¿Quién es más probable que vaya a una cita a ciegas organizada por su madre?"},
    {"q": "¿Quién es más probable que se case el primero/a?"},
    {"q": "¿Quién es más probable que sea perseguido por un perro?"},
    {"q": "¿Quién es más probable que sea el más pesimista?"},
    {"q": "¿Quién es más probable que se haga adicto a las bebidas energéticas?"},
    {"q": "¿Quién es más probable que bese aun mono?"},
    {"q": "¿Quién es más probable que tenga más de 5 hijos?"},
    {"q": "¿Quién es más probable que sea dueño de un negocio pequeño?"},
    {"q": "¿Quién es más probable que desarrolle una aplicación de un millón de dólares?"},
    {"q": "¿Quién es más probable que se quede calvo?"},
    {"q": "¿Quién es más probable que necesite 1 hora para ducharse?"},
    {"q": "¿Quién es más probable que desarrolle un gran juego de mesa?"},
    {"q": "¿Quién es más probable que se case con un extraño en Las Vegas?"},
    {"q": "¿Quién es más probable que pida el postre antes que la cena?"},
    {"q": "¿Quién es más probable que tenga más amantes en los próximos cinco años?"},
    {"q": "¿Quién es más probable que vea los “Baby Looney Tunes”?"},
    {"q": "¿Quién es más probable que suspenda un examen de matemáticas?"},
    {"q": "¿Quién es más probable que se coma su tarta de cumpleaños solo/a?"},
    {"q": "¿Quién es más probable que que se quede en casa un viernes por la noche?"},
    {"q": "¿Quién es más probable que llegue tarde a un evento importante?"},
    {"q": "¿Quién es más probable que permanezca en el baño durante 1 hora todos los días?"},
    {"q": "¿Quién es más probable que se haga adicto a Twitter?"},
    {"q": "¿Quién es más probable que se desmalle si conoce a su celebridad favorita?"},
    {"q": "¿Quién es más probable que se convierta en un super villano?"},
    {"q": "¿Quién es más probable que no reciba regalos por Navidad?"},
    {"q": "¿Quién es más probable que este triste por la muerte de un animal?"},
    {"q": "¿Quién es más probable que rompa una promesa?"},
    {"q": "¿Quién es más probable que rompa el récord mundial?"},
    {"q": "¿Quién es más probable que le pillen diciendo una mentira?"},
    {"q": "¿Quién es más probable que se coma una uña del pie?"},
    {"q": "¿Quién es más probable que se convierta en un orador motivacional?"},
    {"q": "¿Quién es más probable que le caiga un rayo?"},
    {"q": "¿Quién es más probable que cuente cosas sobres las intimidades de sus relaciones anteriores?"},
    {"q": "¿Quién es más probable que tenga miedo al ver una película de terror?"},
    {"q": "¿Quién es más probable que se haga adicto a YouTube?"},
    {"q": "¿Quién es más probable que coma sin lavarse los dientes?"},
    {"q": "¿Quién es más probable que accidentalmente incendie la casa?"},
    {"q": "¿Quién es más probable que sea un terrible embajador de la ONU?"},
    {"q": "¿Quién es más probable que se olvide de su aniversario de boda?"},
    {"q": "¿Quién es más probable que mantenga una relación tóxica?"},
    {"q": "¿Quién es más probable que cause la siguiente guerra mundial?"},
    {"q": "¿Quién es más probable que derrote al “Corona virus”?"},
    {"q": "¿Quién es más probable que contraiga “Corona virus”??"},
    {"q": "¿Quién es más probable que pase mucho tiempo en internet?"},
    {"q": "¿Quién es más probable que se convierta en astronauta?"},
    {"q": "¿Quién es más probable que sea el primero en estar borracho cuando salís de fiesta?"},
    {"q": "¿Quién es más probable que sea un pésimo taxista?"},
    {"q": "¿Quién es más probable que nunca este soltero/a más de 3 meses?"},
    {"q": "¿Quién es más probable que haga el amor en la playa?"},
    {"q": "¿Quién es más probable que actúe ante un flechazo?"},
    {"q": "¿Quién es más probable que se convierta en un terrorista?"},
    {"q": "¿Quién es más probable que haga un pastel para un viaje de la escuela?"},
    {"q": "¿Quién es más probable que este con el corazón roto?"},
    {"q": "¿Quién es más probable que sea un padre tacaño?"},
    {"q": "¿Quién es más probable que mate al amor de su amor platónico?"},
    {"q": "¿Quién es más probable que gaste más dinero en compras?"},
    {"q": "¿Quién es más probable que se coma a su mascota?"},
    {"q": "¿Quién es más probable que se haga adicto a los M&M’s?"},
    {"q": "¿Quién es más probable que se avergüence en público?"},
    {"q": "¿Quién es más probable que se haga adicto al chicle?"},
    {"q": "¿Quién es más probable que pierda los estribos por un asunto insignificante?"},
    {"q": "¿Quién es más probable que vea una película romántica con su amor platónico?"},
    {"q": "¿Quién es más probable que sea la mascota del profesor?"},
    {"q": "¿Quién es más probable que se vaya de casa cuando cumpla los 18?"},
    {"q": "¿Quién es más probable que se lo tome todo literalmente?"},
    {"q": "¿Quién es más probable que coma un insecto?"},
    {"q": "¿Quién es más probable que pregunte por la comida de otra persona?"},
    {"q": "¿Quién es más probable que se case con un millonario?"},
    {"q": "¿Quién es más probable que se case por otra cosa y no por amor?"},
    {"q": "¿Quién es más probable que pase el día de Navidad en un bar?"},
    {"q": "¿Quién es más probable que tenga la manía de hablar consigo mismo?"},
    {"q": "¿Quién es más probable que tenga una bici eléctrica?"},
    {"q": "¿Quién es más probable que se salte ir a la iglesia?"},
    {"q": "¿Quién es más probable que sea un detective horroroso?"},
    {"q": "¿Quién es más probable que tenga fobias raras?"},
    {"q": "¿Quién es más probable que se haga adicto a los video juegos?"},
    {"q": "¿Quién es más probable que coma espaguetis con sirope?"},
    {"q": "¿Quién es más probable que haga puénting?"},
    {"q": "¿Quién es más probable que llame a alguien sin ninguna razón?"},
    {"q": "¿Quién es más probable que se haga gigolo?"},
    {"q": "¿Quién es más probable que vaya al supermercado a por una cosa y se acabe trayendo otras cosas menos esa?"},
    {"q": "¿Quién es más probable que coma cuando este aburrido/a?"},
    {"q": "¿Quién es más probable que tenga un coche eléctrico?"},
    {"q": "¿Quién es más probable que se tiña de muchos colores su pelo a lo largo de su vida?"},
    {"q": "¿Quién es más probable que se haga adicto al chocolate?"},
    {"q": "¿Quién es más probable que sea un padre/madre guay?"},
    {"q": "¿Quién es más probable que tenga el mayor número de hijos?"},
    {"q": "¿Quién es más probable que se convierta en una estrella del deporte?"},
    {"q": "¿Quién es más probable que vea una película romántica con su amor platónico?"},
    {"q": "¿Quién es más probable que convierta en el Jugador Mundial de la FIFA del año?"},
    {"q": "¿Quién es más probable que olvide el cumpleaños de un ser querido?"},
    {"q": "¿Quién es más probable que que llegue 2 horas tarde a su evento?"},
    {"q": "¿Quién es más probable que se coma el mayor número de hamburguesas en menos de 10 minutos?"},
    {"q": "¿Quién es más probable que sea un padre estricto?"},
    {"q": "¿Quién es más probable que se gaste todo en zapatos?"},
    {"q": "¿Quién es más probable que mate a alguien por pizza?"},
    {"q": "¿Quién es más probable que deje muchas pestañas abiertas en su navegador?"},
    {"q": "¿Quién es más probable que se convierta en un artista famoso?"},
    {"q": "¿Quién es más probable que llore por cosas que no tienen mucha importancia?"},
    {"q": "¿Quién es más probable que tenga las mejores notas en los exámenes?"},
    {"q": "¿Quién es más probable que se quede embarazada mientras toma anticonceptivos?"},
    {"q": "¿Quién es más probable que se quede embaraza después de tener un lío de una sola noche?"},
    {"q": "¿Quién es más probable que se haga adicto a ver programas de televisión?"},
    {"q": "¿Quién es más probable que apuñales a sus amigos por la espalda?"},
    {"q": "¿Quién es más probable que sea dueño de un bar?"},
    {"q": "¿Quién es más probable que que se duerma en clase?"},
    {"q": "¿Quién es más probable que se caiga de una silla?"},
    {"q": "¿Quién es más probable que cuelgue en redes sociales una foto en topless?"},
    {"q": "¿Quién es más probable que este castigado?"},
    {"q": "¿Quién es más probable que escuche a escondidas una conversación?"},
    {"q": "¿Quién es más probable que se caiga en un tanque de tiburones?"},
    {"q": "¿Quién es más probable que se quede dormido en el cine?"},
    {"q": "¿Quién es más probable que coma comida rara?"},
    {"q": "¿Quién es más probable que sea amigable con los animales?"},
    {"q": "¿Quién es más probable que se haga profesor?"},
    {"q": "¿Quién es más probable que deambule solo cuando salís de fiesta?"},
    {"q": "¿Quién es más probable que se moleste y diga algo arrepentido?"},
    {"q": "¿Quién es más probable que se enamore del novio/novia de su mejor amigo?"},
    {"q": "¿Quién es más probable que se convierta en un político exitoso?"},
    {"q": "¿Quién es más probable que se convierta en una estrella del pop?"},
    {"q": "¿Quién es más probable que envíe mensajes con contenido sexual estando en clase?"},
    {"q": "¿Quién es más probable que cree el hábito de faltar a trabajar?"},
    {"q": "¿Quién es más probable que cree el hábito de comer mantequilla?"},
    {"q": "¿Quién es más probable que engañe a alguien por internet?"},
    {"q": "¿Quién es más probable que tenga las más terribles habilidades culinarias?"},
    {"q": "¿Quién es más probable que se convierta en un doctor?"},
    {"q": "¿Quién es más probable que vaya a una fiesta solo por la comida?"},
    {"q": "¿Quién es más probable que coma espaguetis con sirope?"},
    {"q": "¿Quién es más probable que sea un cotilla?"},
    {"q": "¿Quién es más probable que coma algo asqueroso por un reto?"},
    {"q": "¿Quién es más probable que haga paracaidismo?"},
    {"q": "¿Quién es más probable que se convierta en un defensor del medio ambiente?"},
    {"q": "¿Quién es más probable que se haga adicto a “Quora”?"},
    {"q": "¿Quién es más probable que llore por una película?"},
    {"q": "¿Quién es más probable que se suicide por un escándalo?"},
    {"q": "¿Quién es más probable que se haga vegetariano/a?"},
    {"q": "¿Quién es más probable que haga un maratón en un solo día de una temporada entera de una serie de TV?"},
    {"q": "¿Quién es más probable que se quede en la cama todo el día?"},
    {"q": "¿Quién es más probable que tenga un matrimonio interracial?"},
    {"q": "¿Quién es más probable que traicione a su equipo?"},
    {"q": "¿Quién es más probable que sea amigable con los animales?"},
    {"q": "¿Quién es más probable que asista a un concierto o festival de música?"},
    {"q": "¿Quién es más probable que sea un terrible vicepresidente?"},
    {"q": "¿Quién es más probable que guarde artículos/ropa que no haya usado en años?"},
    {"q": "¿Quién es más probable que desarrolle el hábito de robar?"},
    {"q": "¿Quién es más probable que se olvide de recoger a los niños del colegio?"},
    {"q": "¿Quién es más probable que sea un jefe horroroso?"},
    {"q": "¿Quién es más probable que que se quede toda la noche despierto pensando?"},
    {"q": "¿Quién es más probable que que perdone a su pareja por haberle engañado?"},
    {"q": "¿Quién es más probable que que se delate a sí mismo jugando al póker?"},
    {"q": "¿Quién es más probable que sea bueno jugando a póker?"},
    {"q": "¿Quién es más probable que se convierta en un banquero de “Wall Street”?"},
    {"q": "¿Quién es más probable que construya un castillo de arena gigante?"},
    {"q": "¿Quién es más probable que se case en la luna?"},
    {"q": "¿Quién es más probable que abra su móvil en un intento de arreglarlo?"},
    {"q": "¿Quién es más probable que viva en una casa encantada?"},
    {"q": "¿Quién es más probable que este de mal humor después de tener un lío de una sola noche?"},
    {"q": "¿Quién es más probable que fume al lado de una señal de “Prohibido fumar”?"},
    {"q": "¿Quién es más probable que se cree la manía de morderse los labios?"},
    {"q": "¿Quién es más probable que se case con su amor de instituto?"},
    {"q": "¿Quién es más probable que vea una película de miedo solo por la noche?"},
    {"q": "¿Quién es más probable que odie el día de San Valentín?"},
    {"q": "¿Quién es más probable que sea un traicionero?"},
    {"q": "¿Quién es más probable que nunca se enamore?"},
    {"q": "¿Quién es más probable que sea un soñador?"},
    {"q": "¿Quién es más probable que vaya de picnic en una cita?"},
    {"q": "¿Quién es más probable que tenga más animales?"},
    {"q": "¿Quién es más probable que desarrolle la manía de chuparse el pulgar?"},
    {"q": "¿Quién es más probable que urge la nariz y se lo coma después?"},
    {"q": "¿Quién es más probable que sea un presidente horroroso?"},
    {"q": "¿Quién es más probable que se caiga por las escaleras mientras sostiene una tarta en las manos?"},
    {"q": "¿Quién es más probable que se haga famoso en internet?"},
    {"q": "¿Quién es más probable que olvide el nombre de las personas?"},
    {"q": "¿Quién es más probable que se quede tirado en sus vacaciones?"},
    {"q": "¿Quién es más probable que desarrolle el hábito de despilfarrar?"},
    {"q": "¿Quién es más probable que se enamore de su jefe/a?"},
    {"q": "¿Quién es más probable que tenga miedo a compartir su opinión en una conversación?"},
    {"q": "¿Quién es más probable que se quede embarazada después de tener un lío de una sola noche?"},
    {"q": "¿Quién es más probable que se quede atrapado en un columpio?"},
    {"q": "¿Quién es más probable que sea dueño de un yate?"},
    {"q": "¿Quién es más probable que gaste todo du dinero en algo estúpido?"},
    {"q": "¿Quién es más probable que tenga un hijo antes de los 18?"},
    {"q": "¿Quién es más probable que nunca celebre su cumpleaños?"},
    {"q": "¿Quién es más probable que se quede hasta tarde despierto discutiendo con los “trolls” en internet?"},
    {"q": "¿Quién es más probable que recuerde que después de la tormenta siempre llega la calma?"},
    {"q": "¿Quién es más probable que le griten sus padres?"},
    {"q": "¿Quién es más probable que coma insectos?"},
    {"q": "¿Quién es más probable que lleve zapatos disparejos por accidente?"},
    {"q": "¿Quién es más probable que sea un rompe corazones?"},
    {"q": "¿Quién es más probable que sea un actor/actriz horroroso?"},
    {"q": "¿Quién es más probable que se quede dormido en el autobús y se pase su parada?"},
    {"q": "¿Quién es más probable que desarrolle el hábito de recogerse el pelo?"},
    {"q": "¿Quién es más probable que se convierta en un jugador de apuestas?"},
    {"q": "¿Quién es más probable que se olvide lo que le ha contado a alguien?"},
    {"q": "¿Quién es más probable que sea un soñador?"},
    {"q": "¿Quién es más probable que coma sin lavarse los dientes?"},
    {"q": "¿Quién es más probable que coma comida de gato?"},
    {"q": "¿Quién es más probable que se retoque todo su maquillaje antes de algo importante?"},
    {"q": "¿Quién es más probable que hackee la red social de su ex?"},
    {"q": "¿Quién es más probable que llore en un lugar público?"},
    {"q": "¿Quién es más probable que sea un jefe/a horroroso?"},
    {"q": "¿Quién es más probable que se coma su tarta de cumpleaños solo/a?"},
    {"q": "¿Quién es más probable que llegue tarde a clase?"},
    {"q": "¿Quién es más probable que filtre sus fotos desnudas?"},
    {"q": "¿Quién es más probable que tenga más de dos esposas en toda su vida?"},
    {"q": "¿Quién es más probable que le arrebate el novio/a a alguien?"},
    {"q": "¿Quién es más probable que tenga una habitación desordenada?"},
    {"q": "¿Quién es más probable que se vaya y nunca vuelva?"},
    {"q": "¿Quién es más probable que trabaje para Google?"},
    {"q": "¿Quién es más probable que robe un móvil viejo “Nokia”?"},
    {"q": "¿Quién es más probable que agote la batería de su teléfono?"},
    {"q": "¿Quién es más probable que lo encuentres en una librería?"},
    {"q": "¿Quién es más probable que olvide un evento importante?"},
    {"q": "¿Quién es más probable que siga utilizando su nombre de soltera?"},
    {"q": "¿Quién es más probable que se haga adicto a fumar?"},
    {"q": "¿Quién es más probable que vaya a una fiesta en pijama?"},
    {"q": "¿Quién es más probable que se coma todo sin dejar restos?"},
    {"q": "¿Quién es más probable que se convierta en un granjero?"},
    {"q": "¿Quién es más probable que sea expulsado de la escuela?"},
    {"q": "¿Quién es más probable que bese a una rana?"},
    {"q": "¿Quién es más probable que se gaste todo en maquillaje?"},
    {"q": "¿Quién es más probable que se convierta en un atleta profesional?"},
    {"q": "¿Quién es más probable que saque las mejores notas para entrar en la universidad?"},
    {"q": "¿Quién es más probable que desarrolle el hábito de comerse las uñas?"},
    {"q": "¿Quién es más probable que tenga el mayor número de amigos en Facebook?"},
    {"q": "¿Quién es más probable que tenga un tatuaje muy común?"},
    {"q": "¿Quién es más probable que se fugue con un amante?"},
    {"q": "¿Quién es más probable que se convierta en un columnista de cotilleos?"},
    {"q": "¿Quién es más probable que se vaya de excursión con extraños?"},
    {"q": "¿Quién es más probable que mate a un perro y lo retrasmita en directo?"},
    {"q": "¿Quién es más probable que se pelee con un amigo por algo estúpido?"},
    {"q": "¿Quién es más probable que que sea dueño de un Lamborghini?"},
    {"q": "¿Quién es más probable que se haga adicto a beber agua con gas?"},
    {"q": "¿Quién es más probable que sea arrestado?"},
    {"q": "¿Quién es más probable que olvide el cumpleaños de un ser querido?"},
    {"q": "¿Quién es más probable que vaya a la cárcel por haber hecho algo estúpido?"},
    {"q": "¿Quién es más probable que acabe en prisión?"},
    {"q": "¿Quién es más probable que que tenga el tatuaje más vergonzoso?"},
    {"q": "¿Quién es más probable que se convierta en el autor con más libros vendidos?"},
]
